use_frameworks!

target 'BatSignal_Example' do
  pod 'BatSignal', :path => '../'

  target 'BatSignal_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
